# Site settings
title: aimeeb
author: Aimee
email: barciaai@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  allthethings!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aimeeb.com" # the base hostname & protocol for your site
twitter: https://twitter.com/_aimeeb
github:  https://github.com/AimeeRose
instagram: https://instagram.com/abarciauskas/

# Build settings
markdown: kramdown
